### ISSUE TITLE
Guides as source

### ISSUE THREAD

**Issue by joreg** [thagrol/Guides#19]
First thanks, for those excellent guides!

I wonder if there is any chance to have them available on a website where we can directly link to individual chapters? Currently, I see no way of pointing someone to specific information.

**Comment by thagrol** [comment]
I'm afraid that's unlikey to happen though I may investigate as time, energy, and motivation permit.

**Comment by thagrol** [comment]
HTML and other formats are not goingto happen. Consensus is that pdf only is fine: https://forums.raspberrypi.com/viewtopic.php?t=343525
